### ISSUE TITLE
coverage not being reported in PR

### ISSUE THREAD

**Issue by sndrs** [mattallty/jest-github-action#16]
hi there,

i'm trying to get the bottom of why coverage is not being reported in PRs (e.g. https://github.com/guardian/consent-management-platform/pull/169) but i'm stuck!

here's a successful run:
https://github.com/guardian/consent-management-platform/pull/169/checks?check_run_id=853812425

it looks like there are no errors, but there no comment being posted. 

this is the config for the action:
https://github.com/guardian/consent-management-platform/blob/f8b139666606f45f32c6198cf564004e1fbe6885/.github/workflows/CI.yml#L8-L27

am i doing something stupid?

thanks!

alex

**Comment by ash-r1** [comment]
@sndrs 

I'm not sure, but I think you may need to add the configuration below:

```
  pull_request:
    branches: [ '**' ]
```

**Comment by sndrs** [comment]
thanks @ash-r1 – went with @codecov in the end 👍
