### ISSUE TITLE
Jest results/annotations job is added to the wrong workflow

### ISSUE THREAD

**Issue by wopian** [mattallty/jest-github-action#18]
I have four GitHub Actions workflows with one of them for testing with Jest using this action. However, the job is appended to the first(?) workflow started instead of the workflow the action was started from.

For example:
- https://github.com/wopian/preferred-locale/actions/runs/182685605
  - Jest results added to the `Build & Size Limit` workflow but generated from an action in the `Unit Tests` workflow
- https://github.com/wopian/kitsu/runs/910633972
  - Jest results added to the `Size Limit` workflow but generated from an action in the `Unit Tests` workflow

While the generated job fails, it does not cause the workflow it was added to to fail (`Build & Size Limit` on `preferred-locale` still passed despite the error) so you have to do a lot of clicking to find the workflow containing the test failure annotations while the jobs in the unit test workflow just say "some tests failed"

---

- Workflow file: https://github.com/wopian/kitsu/actions/runs/182675118/workflow
- jest-github-action: v1.0.3

**Comment by negebauer** [comment]
I'm also seeing this issue where the jest annotation is added to a different workflow

**Comment by negebauer** [comment]
It's also generating another error, annotations are being overwritten.
If you have two workflows that generate annotations with this only one is shown in the PR

**Comment by ckissane** [comment]
Unfortunately this isn't fixable with GitHub's current API:
See: https://github.community/t/specify-check-suite-when-creating-a-checkrun/118380/6
