### ISSUE TITLE
Handle 404 when GET'ing issue comments

### ISSUE THREAD

**Issue by probablyup** [mattallty/jest-github-action#9]
If an annotation was made on a file that wasn't changed in the PR, there will be no corresponding comment. In this case the 404 from that endpoint should be ignored

Edit: I actually just noticed the coverage comment was never added. Perhaps that's the issue.

Error:

```
RequestError [HttpError]: Not Found
##[error]Not Found
    at /home/runner/work/_actions/mattallty/jest-github-action/v1.0.2/dist/index.js:1:153269
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 08 Jun 2020 15:31:49 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0400:29AE:547485:DA11A7:5EDE59E5',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '993',
    'x-ratelimit-reset': '1591633048',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/[redacted]/issues/0/comments?per_page=100',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue'
}
```

**Comment by wmonk** [comment]
I think the issue here is that the pull request ID isn't being reported by `@github/actions.Context`, so defaults to `0`:

https://github.com/mattallty/jest-github-action/blob/40eafe1b6e3924992dd7e3b0a07e70dfdff1d52f/src/action.ts#L178-L180

I had a look at the code in `@github/actions` and can see that it's a nullable value, but am unsure why...

**Comment by crucialfelix** [comment]
I think the first time it posts coverage it fails with the 404 because there is nothing to delete. Unfortunately now I can't manage to get it to complete at all, even when I turn off coverage.

**Comment by wmonk** [comment]
It took me ages, but I've worked out why (for our setup at least)! We had our workflow setup with ```on: [push]```, which means the action run is tied to a commit. If you change ```push``` to ```pull_request``` then it's tied to a PR, and it'll find the issue number fine.

**Comment by crucialfelix** [comment]
I love you @wmonk 

<img width="406" alt="Screen Shot 2020-06-12 at 3 13 53 PM" src="https://user-images.githubusercontent.com/218738/84506265-62878100-acbf-11ea-9473-4ba060932c2f.png">
